version: '3'

services:
  flask:
    container_name: cicd
    build:
      context: .
      dockerfile: ./app/dockerfile
    ports:
      - "5000:5000"
    privileged: true
    volumes:
      - "./app:/app"
    tty: true
    environment:
      TZ: Asia/Tokyo
      FLASK_ENV: 'development'    #デバッグモードON
      FLASK_APP: 'app.py'         #起動用アプリの設定
    command: flask run --host 0.0.0.0 --port 5000

